package ui;

public enum ButtonId
{
	LOG_ID, OPTION_ID, TURN_ID, QUIT_ID, DETAILS_ID, BACK_ID, ADD_ID, LEFT_ID, RIGHT_ID, MOVE_FARMERS_ID,
	MOVE_BUILDERS_ID, MOVE_GATHERERS_ID, TRANSFER_ID, MOVE_MESSENGERS_ID, MOVE_ENVOYS_ID, 
	MOVE_CARRIERS_ID, MOVE_SOLDIERS_ID, ADD_PROJECT_ID, CHANGE_PROJECT_ID, BUMP_PROJECT_ID;
}
